# Generated by Django 5.0.1 on 2024-01-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UAV',
            new_name='Product',
        ),
    ]
